-- H2 2.1.214;
;             
CREATE USER IF NOT EXISTS "APPUSERDB" SALT '7c950a61f520e516' HASH 'bfdc0ab43907ad7f8d579814c9c30c8a3af1619af8c8854ea198af9c5b9f6a53' ADMIN;  
CREATE MEMORY TABLE "PUBLIC"."TELEFONO"(
    "ID" UUID NOT NULL,
    "CITYCODE" CHARACTER VARYING(255),
    "COUNTRYCODE" CHARACTER VARYING(255),
    "NUMBER" CHARACTER VARYING(255)
); 
ALTER TABLE "PUBLIC"."TELEFONO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TELEFONO;
CREATE MEMORY TABLE "PUBLIC"."USUARIO"(
    "ID" UUID NOT NULL,
    "CREATED" TIMESTAMP(6),
    "EMAIL" CHARACTER VARYING(255),
    "IS_ACTIVE" BOOLEAN,
    "LAST_LOGIN" TIMESTAMP(6),
    "MODIFIED" TIMESTAMP(6),
    "NAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255),
    "TOKEN" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."USUARIO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USUARIO; 
CREATE MEMORY TABLE "PUBLIC"."USUARIO_PHONES"(
    "USUARIO_ID" UUID NOT NULL,
    "PHONES_ID" UUID NOT NULL
);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USUARIO_PHONES;          
ALTER TABLE "PUBLIC"."USUARIO_PHONES" ADD CONSTRAINT "PUBLIC"."UK_5BQC1344TAX0V7W58423TMXXQ" UNIQUE("PHONES_ID");             
ALTER TABLE "PUBLIC"."USUARIO_PHONES" ADD CONSTRAINT "PUBLIC"."FKP1C8DTI15OU6BKMM9I6K6GE42" FOREIGN KEY("USUARIO_ID") REFERENCES "PUBLIC"."USUARIO"("ID") NOCHECK;            
ALTER TABLE "PUBLIC"."USUARIO_PHONES" ADD CONSTRAINT "PUBLIC"."FK9Q91BVLEP54I6QYQX71NLIP3H" FOREIGN KEY("PHONES_ID") REFERENCES "PUBLIC"."TELEFONO"("ID") NOCHECK;            
